export const keyboardData = [
  [
    {
      code: 'Backquote',
      state: false,
      lang: { en: '`', ru: 'ё' },
      size: 'middle',
    },
    {
      code: 'Digit1',
      state: false,
      lang: { en: '1', ru: '1' },
      size: 'middle',
    },
    {
      code: 'Digit2',
      state: false,
      lang: { en: '2', ru: '2' },
      size: 'middle',
    },
    {
      code: 'Digit3',
      state: false,
      lang: { en: '3', ru: '3' },
      size: 'middle',
    },
    {
      code: 'Digit4',
      state: false,
      lang: { en: '4', ru: '4' },
      size: 'middle',
    },
    {
      code: 'Digit5',
      state: false,
      lang: { en: '5', ru: '5' },
      size: 'middle',
    },
    {
      code: 'Digit6',
      state: false,
      lang: { en: '6', ru: '6' },
      size: 'middle',
    },
    {
      code: 'Digit7',
      state: false,
      lang: { en: '7', ru: '7' },
      size: 'middle',
    },
    {
      code: 'Digit8',
      state: false,
      lang: { en: '8', ru: '8' },
      size: 'middle',
    },
    {
      code: 'Digit9',
      state: false,
      lang: { en: '9', ru: '9' },
      size: 'middle',
    },
    {
      code: 'Digit0',
      state: false,
      lang: { en: '0', ru: '0' },
      size: 'middle',
    },
    {
      code: 'Minus',
      state: false,
      lang: { en: '-', ru: '-' },
      size: 'middle',
    },
    {
      code: 'Equal',
      state: false,
      lang: { en: '=', ru: '=' },
      size: 'middle',
    },
    {
      code: 'Backspace',
      state: true,
      lang: { en: 'Backspace', ru: 'Backspace' },
      size: 's-large',
    },
  ],
  [
    {
      code: 'Tab',
      state: true,
      lang: { en: 'Tab', ru: 'Tab' },
      size: 'xs-large',
    },
    {
      code: 'KeyQ',
      state: false,
      lang: { en: 'q', ru: 'й' },
      size: 'middle',
    },
    {
      code: 'KeyW',
      state: false,
      lang: { en: 'w', ru: 'ц' },
      size: 'middle',
    },
    {
      code: 'KeyE',
      state: false,
      lang: { en: 'e', ru: 'у' },
      size: 'middle',
    },
    {
      code: 'KeyR',
      state: false,
      lang: { en: 'r', ru: 'к' },
      size: 'middle',
    },
    {
      code: 'KeyT',
      state: false,
      lang: { en: 't', ru: 'е' },
      size: 'middle',
    },
    {
      code: 'KeyY',
      state: false,
      lang: { en: 'y', ru: 'н' },
      size: 'middle',
    },
    {
      code: 'KeyU',
      state: false,
      lang: { en: 'u', ru: 'г' },
      size: 'middle',
    },
    {
      code: 'KeyI',
      state: false,
      lang: { en: 'i', ru: 'ш' },
      size: 'middle',
    },
    {
      code: 'KeyO',
      state: false,
      lang: { en: 'o', ru: 'щ' },
      size: 'middle',
    },
    {
      code: 'KeyP',
      state: false,
      lang: { en: 'p', ru: 'з' },
      size: 'middle',
    },
    {
      code: 'BracketLeft',
      state: false,
      lang: { en: '[', ru: 'х' },
      size: 'middle',
    },
    {
      code: 'BracketRight',
      state: false,
      lang: { en: ']', ru: 'ъ' },
      size: 'middle',
    },
    {
      code: 'Backslash',
      state: false,
      lang: { en: '\\', ru: '\\' },
      size: 'middle',
    },
    {
      code: 'Delete',
      state: true,
      lang: { en: 'Delete', ru: 'Delete' },
      size: 'middle',
    },
  ],
  [
    {
      code: 'CapsLock',
      state: true,
      lang: { en: 'Caps Lock', ru: 'Caps Lock' },
      size: 'm-large',
    },
    {
      code: 'KeyA',
      state: false,
      lang: { en: 'a', ru: 'ф' },
      size: 'middle',
    },
    {
      code: 'KeyS',
      state: false,
      lang: { en: 's', ru: 'ы' },
      size: 'middle',
    },
    {
      code: 'KeyD',
      state: false,
      lang: { en: 'd', ru: 'в' },
      size: 'middle',
    },
    {
      code: 'KeyF',
      state: false,
      lang: { en: 'f', ru: 'а' },
      size: 'middle',
    },
    {
      code: 'KeyG',
      state: false,
      lang: { en: 'g', ru: 'п' },
      size: 'middle',
    },
    {
      code: 'KeyH',
      state: false,
      lang: { en: 'h', ru: 'р' },
      size: 'middle',
    },
    {
      code: 'KeyJ',
      state: false,
      lang: { en: 'j', ru: 'о' },
      size: 'middle',
    },
    {
      code: 'KeyK',
      state: false,
      lang: { en: 'k', ru: 'л' },
      size: 'middle',
    },
    {
      code: 'KeyL',
      state: false,
      lang: { en: 'l', ru: 'д' },
      size: 'middle',
    },
    {
      code: 'Semicolon',
      state: false,
      lang: { en: ';', ru: 'ж' },
      size: 'middle',
    },
    {
      code: 'Quote',
      state: false,
      lang: { en: "'", ru: 'э' },
      size: 'middle',
    },
    {
      code: 'Enter',
      state: true,
      lang: { en: 'Enter', ru: 'Enter' },
      size: 'm-large',
    },
  ],
  [
    {
      code: 'ShiftLeft',
      state: true,
      lang: { en: 'Shift', ru: 'Shift' },
      size: 'l-large',
    },
    {
      code: 'KeyZ',
      state: false,
      lang: { en: 'z', ru: 'я' },
      size: 'middle',
    },
    {
      code: 'KeyX',
      state: false,
      lang: { en: 'x', ru: 'ч' },
      size: 'middle',
    },
    {
      code: 'KeyC',
      state: false,
      lang: { en: 'c', ru: 'с' },
      size: 'middle',
    },
    {
      code: 'KeyV',
      state: false,
      lang: { en: 'v', ru: 'м' },
      size: 'middle',
    },
    {
      code: 'KeyB',
      state: false,
      lang: { en: 'b', ru: 'и' },
      size: 'middle',
    },
    {
      code: 'KeyN',
      state: false,
      lang: { en: 'n', ru: 'т' },
      size: 'middle',
    },
    {
      code: 'KeyM',
      state: false,
      lang: { en: 'm', ru: 'ь' },
      size: 'middle',
    },
    {
      code: 'Comma',
      state: false,
      lang: { en: ',', ru: 'б' },
      size: 'middle',
    },
    {
      code: 'Period',
      state: false,
      lang: { en: '.', ru: 'ю' },
      size: 'middle',
    },
    {
      code: 'Slash',
      state: false,
      lang: { en: '/', ru: '.' },
      size: 'middle',
    },
    {
      code: 'ArrowUp',
      state: true,
      lang: { en: '⯅', ru: '⯅' },
      size: 'middle',
    },
    {
      code: 'ShiftRight',
      state: true,
      lang: { en: 'Shift', ru: 'Shift' },
      size: 'l-large',
    },
  ],
  [
    {
      code: 'ControlLeft',
      state: true,
      lang: { en: 'Ctrl', ru: 'Ctrl' },
      size: 'xxs-large',
    },
    {
      code: 'MetaLeft',
      state: true,
      lang: { en: 'Win', ru: 'Win' },
      size: 'middle',
    },
    {
      code: 'AltLeft',
      state: true,
      lang: { en: 'Alt', ru: 'Alt' },
      size: 'middle',
    },
    {
      code: 'Space',
      state: true,
      lang: { en: '', ru: '' },
      size: 'xl-large',
    },
    {
      code: 'AltRight',
      state: true,
      lang: { en: 'Alt', ru: 'Alt' },
      size: 'middle',
    },
    {
      code: 'ControlRight',
      state: true,
      lang: { en: 'Ctrl', ru: 'Ctrl' },
      size: 'xxs-large',
    },
    {
      code: 'ArrowLeft',
      state: true,
      lang: { en: '⯇', ru: '⯇' },
      size: 'middle',
    },
    {
      code: 'ArrowDown',
      state: true,
      lang: { en: '⯆', ru: '⯆' },
      size: 'middle',
    },
    {
      code: 'ArrowRight',
      state: true,
      lang: { en: '⯈', ru: '⯈' },
      size: 'middle',
    },

  ],
];
